trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    # Run your script here
    ./2_Scripting/solaboratebash.sh  # Replace with the actual script file name
  displayName: 'Runing out Script'
